# Generated by Django 3.0.3 on 2020-03-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0002_plantcollections_plantcollectionspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantcollectionspage',
            name='collection_doc',
        ),
        migrations.AddField(
            model_name='plantcollections',
            name='collection_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
