# Generated by Django 3.0.3 on 2020-03-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0011_generalindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalindexpage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='generalpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Thumbnail will display on the index page along with the title of this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
