# Generated by Django 3.0.10 on 2020-09-30 16:36

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_faqpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBGHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_override', models.BooleanField(default=False, help_text='Override hours.js script and manually set all hours options')),
                ('garden_open', models.TimeField(help_text='When override set to True, this time will be shown as the time the garden opens')),
                ('garden_close', models.TimeField(help_text='When override set to True, this time will be shown as the time the garden closes')),
                ('additional_message', models.CharField(help_text="Message under the hours; e.g. 'Last entry at 3:30 PM'", max_length=200)),
                ('additional_emphatic_mesg', models.CharField(help_text='Message under hours in RED text', max_length=200)),
                ('holiday_party_close_time', models.DateTimeField(help_text='Day and time we close for Holiday Party in December')),
                ('gad_dates', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Dates when Garden After Dark takes place')),
            ],
        ),
    ]
