# Generated by Django 3.0.10 on 2020-09-30 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rbghours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rbghours',
            options={'verbose_name_plural': 'RBG Hours'},
        ),
        migrations.RemoveField(
            model_name='rbghours',
            name='gad_dates',
        ),
        migrations.AddField(
            model_name='rbghours',
            name='gad_end',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when Garden After Dark ends'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rbghours',
            name='gad_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when Garden After Dark begins'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='additional_emphatic_mesg',
            field=models.CharField(blank=True, help_text='Message under hours in RED text', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='additional_message',
            field=models.CharField(blank=True, help_text="Message under the hours; e.g. 'Last entry at 3:30 PM'", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='garden_close',
            field=models.TimeField(blank=True, help_text='When override set to True, this time will be shown as the time the garden closes', null=True),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='garden_open',
            field=models.TimeField(blank=True, help_text='When override set to True, this time will be shown as the time the garden opens', null=True),
        ),
    ]
