# Generated by Django 3.0.10 on 2020-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200930_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbghours',
            name='name',
            field=models.CharField(default='Normal hours', help_text='Create a name for this set of hours', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='gad_end',
            field=models.DateField(help_text='Date when Garden After Dark ends', verbose_name='Garden After Dark end date'),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='gad_start',
            field=models.DateField(help_text='Date when Garden After Dark begins', verbose_name='Garden After Dark start date'),
        ),
    ]
