# Generated by Django 3.0.10 on 2020-09-30 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200930_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.RBGHours'),
        ),
    ]
