# Generated by Django 3.0.10 on 2020-09-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepage_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbghours',
            name='gad_end',
        ),
        migrations.RemoveField(
            model_name='rbghours',
            name='gad_start',
        ),
    ]
