# Generated by Django 3.0.10 on 2020-09-30 21:49

from django.db import migrations
import django.utils.timezone
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200930_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbghours',
            name='gad_dates',
            field=wagtail.core.fields.StreamField([('date', wagtail.core.blocks.DateBlock(help_text='Date that GAD takes place', verbose_name='Garden After Dark date'))], default='', help_text='Choose the dates of GAD. If there are many, using the manual override might be easier'),
            preserve_default=False,
        ),
    ]
