# Generated by Django 3.0.10 on 2020-12-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20201215_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbghours',
            name='holiday_party_close_time',
            field=models.DateTimeField(blank=True, help_text='Day and time we close for Holiday Party in December', null=True),
        ),
    ]
