# Generated by Django 3.2.9 on 2022-11-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0067_auto_20221102_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='custom_css',
            field=models.ForeignKey(blank=True, help_text='Upload a CSS file to apply custom styling to this page. Note that editing an existing document will apply the changes to ALL pages where the document is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Custom CSS'),
        ),
        migrations.AlterField(
            model_name='generalindexpage',
            name='custom_css',
            field=models.ForeignKey(blank=True, help_text='Upload a CSS file to apply custom styling to this page. Note that editing an existing document will apply the changes to ALL pages where the document is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Custom CSS'),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='custom_css',
            field=models.ForeignKey(blank=True, help_text='Upload a CSS file to apply custom styling to this page. Note that editing an existing document will apply the changes to ALL pages where the document is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Custom CSS'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='custom_css',
            field=models.ForeignKey(blank=True, help_text='Upload a CSS file to apply custom styling to this page. Note that editing an existing document will apply the changes to ALL pages where the document is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Custom CSS'),
        ),
        migrations.AlterField(
            model_name='plantcollectionspage',
            name='custom_css',
            field=models.ForeignKey(blank=True, help_text='Upload a CSS file to apply custom styling to this page. Note that editing an existing document will apply the changes to ALL pages where the document is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Custom CSS'),
        ),
        migrations.AlterField(
            model_name='retailpartnerpage',
            name='custom_css',
            field=models.ForeignKey(blank=True, help_text='Upload a CSS file to apply custom styling to this page. Note that editing an existing document will apply the changes to ALL pages where the document is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Custom CSS'),
        ),
        migrations.AlterField(
            model_name='twocolumngeneralpage',
            name='custom_css',
            field=models.ForeignKey(blank=True, help_text='Upload a CSS file to apply custom styling to this page. Note that editing an existing document will apply the changes to ALL pages where the document is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Custom CSS'),
        ),
    ]
