# Generated by Django 4.1.3 on 2023-01-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_faqpage_dialog_content_faqpage_dialog_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='dialog_display',
            field=models.BooleanField(blank=True, default=False, help_text='Should this dialog be displayed?', null=True),
        ),
        migrations.AlterField(
            model_name='generalindexpage',
            name='dialog_display',
            field=models.BooleanField(blank=True, default=False, help_text='Should this dialog be displayed?', null=True),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='dialog_display',
            field=models.BooleanField(blank=True, default=False, help_text='Should this dialog be displayed?', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='dialog_display',
            field=models.BooleanField(blank=True, default=False, help_text='Should this dialog be displayed?', null=True),
        ),
        migrations.AlterField(
            model_name='plantcollectionspage',
            name='dialog_display',
            field=models.BooleanField(blank=True, default=False, help_text='Should this dialog be displayed?', null=True),
        ),
        migrations.AlterField(
            model_name='retailpartnerpage',
            name='dialog_display',
            field=models.BooleanField(blank=True, default=False, help_text='Should this dialog be displayed?', null=True),
        ),
        migrations.AlterField(
            model_name='twocolumngeneralpage',
            name='dialog_display',
            field=models.BooleanField(blank=True, default=False, help_text='Should this dialog be displayed?', null=True),
        ),
    ]
