# Generated by Django 4.2.17 on 2025-01-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_alter_faqpage_body_alter_footertext_locale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
                ('temperature', models.IntegerField()),
            ],
        ),
    ]
