# Generated by Django 4.2.17 on 2025-01-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_currentweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslides',
            name='embed',
            field=models.URLField(blank=True, help_text='Link to external video URL', null=True),
        ),
    ]
