# Generated by Django 4.2.17 on 2025-02-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_eventslides_embed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rbghours',
            options={'ordering': ['-last_modified'], 'verbose_name_plural': 'RBG Hours'},
        ),
        migrations.RemoveField(
            model_name='rbghours',
            name='allow_override',
        ),
        migrations.RemoveField(
            model_name='rbghours',
            name='gad_dates',
        ),
        migrations.RemoveField(
            model_name='rbghours',
            name='holiday_party_close_time',
        ),
        migrations.AddField(
            model_name='rbghours',
            name='garden_closed_message',
            field=models.CharField(blank=True, default='The Garden is closed now', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rbghours',
            name='garden_open_message',
            field=models.CharField(blank=True, default='The Garden is open', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rbghours',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='garden_close',
            field=models.TimeField(blank=True, help_text='The time the garden closes', null=True),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='garden_open',
            field=models.TimeField(blank=True, help_text='The time the garden opens', null=True),
        ),
    ]
