# Generated by Django 4.2.20 on 2025-05-03 19:48

from django.db import migrations, models
import django.db.models.deletion
import home.custom_fields
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_alter_generalpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hours',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hours_section_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='This text is displayed within the hours section, just beneath the hours', null=True),
        ),
        migrations.AddField(
            model_name='rbghours',
            name='days_of_week',
            field=home.custom_fields.ChoiceArrayField(base_field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]), blank=True, help_text='Select the days of the week this set of hours applies to', null=True, size=None),
        ),
        migrations.AddField(
            model_name='rbghours',
            name='months_of_year',
            field=home.custom_fields.ChoiceArrayField(base_field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')]), blank=True, help_text='Select the months of the year this set of hours applies to', null=True, size=None),
        ),
        migrations.CreateModel(
            name='RBGHoursOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rbghours')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbg_hours', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
