# Generated by Django 4.2.20 on 2025-05-02 18:48

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_alter_generalpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hours_section_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='This text is dislayed within the hours section, just beneath the hours', null=True),
        ),
    ]
