# Generated by Django 4.2.20 on 2025-06-21 17:13

from django.db import migrations, models
import home.custom_fields
import home.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_rbghours_garden_closed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rbghours',
            options={'ordering': ['last_modified'], 'verbose_name_plural': 'RBG Hours'},
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='additional_emphatic_mesg',
            field=wagtail.fields.RichTextField(blank=True, help_text='Message under hours in RED text', null=True),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='additional_message',
            field=wagtail.fields.RichTextField(blank=True, help_text="Message under the hours; e.g. 'Last entry at 3:30 PM'", null=True),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='days_of_week',
            field=home.custom_fields.ChoiceArrayField(base_field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]), blank=True, default=home.models.default_days_of_week, help_text='Select the days of the week this set of hours applies to', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rbghours',
            name='months_of_year',
            field=home.custom_fields.ChoiceArrayField(base_field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')]), blank=True, default=home.models.default_months_of_year, help_text='Select the months of the year this set of hours applies to', null=True, size=None),
        ),
    ]
