# Generated by Django 4.2.20 on 2025-06-21 17:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_alter_rbghours_options_homepage_hours_section_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hours_section_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='This text is displayed within the hours section, just beneath the hours', null=True),
        ),
    ]
