# Generated by Django 4.2.20 on 2025-06-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_homepage_hours_section_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbghours',
            name='garden_closed',
        ),
    ]
