# Generated by Django 4.2.20 on 2025-06-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_remove_rbghours_garden_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rbghours',
            options={'ordering': ['-last_modified'], 'verbose_name_plural': 'RBG Hours'},
        ),
    ]
