# Generated by Django 5.2.9 on 2025-12-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_alter_generalindexpage_body_alter_generalpage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='visit_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_page_visit_images', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whats_blooming_now_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_page_blooming_now_images', to='wagtailimages.image'),
        ),
    ]
