# Generated by Django 5.2.11 on 2026-02-24 19:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_alter_generalpage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar', wagtail.fields.StreamField([('group', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title/tooltip.', 'max_length': 140, 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Django URL name, e.g. 'plants:plant-map'.", 'max_length': 200, 'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page that implements RoutablePageMixin.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': "Routable route name, e.g. 'event_by_category'.", 'max_length': 120, 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'JSON list of positional args, e.g. ["art-exhibits"].', 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'help_text': 'JSON object of keyword args, e.g. {"slug": "art-exhibits"}.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 1), ('description', 2), ('open_in_new_tab', 3), ('internal_page', 4), ('external_url', 5), ('named_url', 6), ('routable_page', 7), ('route_name', 8), ('route_args_json', 9), ('route_kwargs_json', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('label', 1), ('description', 2), ('open_in_new_tab', 3), ('internal_page', 4), ('external_url', 5), ('named_url', 6), ('routable_page', 7), ('route_name', 8), ('route_args_json', 9), ('route_kwargs_json', 10)]], {'help_text': 'Optional: make the group heading link somewhere.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional identifier, e.g. 'visit'.", 'max_length': 40, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 12), ('group_link', 13), ('key', 14)]], {})})),
                ('top_links', wagtail.fields.StreamField([('link', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title/tooltip.', 'max_length': 140, 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Django URL name, e.g. 'plants:plant-map'.", 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page that implements RoutablePageMixin.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Routable route name, e.g. 'event_by_category'.", 'max_length': 120, 'required': False}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'JSON list of positional args, e.g. ["art-exhibits"].', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'JSON object of keyword args, e.g. {"slug": "art-exhibits"}.', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('label', 0), ('description', 1), ('open_in_new_tab', 2), ('internal_page', 3), ('external_url', 4), ('named_url', 5), ('routable_page', 6), ('route_name', 7), ('route_args_json', 8), ('route_kwargs_json', 9)]], {})}, help_text='Optional links rendered on the right side (e.g. JOIN / GIVE).')),
                ('show_search', models.BooleanField(default=True)),
                ('search_placeholder', models.CharField(default='Search', max_length=60)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
