# Generated by Django 5.2.11 on 2026-02-24 19:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_seed_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='navbar',
            field=wagtail.fields.StreamField([('group', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional identifier, e.g. 'visit'.", 'max_length': 40, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title/tooltip.', 'max_length': 140, 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Django URL name, e.g. 'plants:plant-map'.", 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page that implements RoutablePageMixin.', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': "Routable route name, e.g. 'event_by_category'.", 'max_length': 120, 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'help_text': 'JSON list of positional args, e.g. ["art-exhibits"].', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'JSON object of keyword args, e.g. {"slug": "art-exhibits"}.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 2), ('description', 3), ('open_in_new_tab', 4), ('internal_page', 5), ('external_url', 6), ('named_url', 7), ('routable_page', 8), ('route_name', 9), ('route_args_json', 10), ('route_kwargs_json', 11)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('link', 12)]], {'help_text': 'Optional: make the group heading link somewhere.', 'max_num': 1, 'required': False}), 14: ('wagtail.blocks.ListBlock', (12,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('key', 1), ('group_link', 13), ('links', 14)]], {})}),
        ),
    ]
