# Generated by Django 5.2.12 on 2026-03-17 18:01

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_alter_faqpage_body_alter_generalindexpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailpartnerpage',
            name='retail_partners',
            field=wagtail.fields.StreamField([('retail_partner', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 75}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 30, 'required': False}), 3: ('wagtail.blocks.IntegerBlock', (), {'max_value': 99950, 'min_value': 501, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'validators': [django.core.validators.RegexValidator('\\(?[0-9]{3}\\)?[-|\\s]?[0-9]{3}-?[0-9]{4}', 'Please enter a valid phone number')]}), 5: ('wagtail.blocks.StructBlock', [[('street_address', 1), ('city', 2), ('zipcode', 3), ('phone', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'bold', 'italic', 'link', 'ol', 'ul', 'lead'], 'help_text': 'Headings must be used sequentially. In other words, if you want to use an h3 it must appear after an h2 and be part of the same context/section. Do not use heading tags (e.g. h2, h3) to emphasize text. Lead can be used to make slightly larger text for emphasis.'}), 9: ('wagtail.blocks.StructBlock', [[('name', 0), ('addresses', 6), ('url', 7), ('info', 8)]], {})}),
        ),
    ]
