# Generated by Django 3.0.10 on 2020-10-08 21:25

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalpagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpage',
            name='body',
            field=wagtail.core.fields.StreamField([('green_heading', wagtail.core.blocks.CharBlock(help_text='Green centered text', max_length=200)), ('paragraph', wagtail.core.blocks.StructBlock([('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')])), ('paragraph', wagtail.core.blocks.RichTextBlock())], classname='paragraph', required=True)), ('tan_bg_text', wagtail.core.blocks.RichTextBlock(classname='paragraph', help_text='Paragraph with a tan background', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.core.blocks.RawHTMLBlock(required=False)), ('image_list', wagtail.core.blocks.StructBlock([('list_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('title', wagtail.core.blocks.CharBlock(help_text='Displayed right of image in h2 tag, centered and uppercase', label='Title', max_length=200)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Displayed under title, centered and green', label='Subtitle', max_length=200)), ('text', wagtail.core.blocks.RichTextBlock(label='Text')), ('link_url', wagtail.core.blocks.URLBlock(help_text='If provided, the link will be applied to the image', label='Link URL', max_length=200, required=False))]), help_text='Images displayed with text to the right, all with a tan background', label='List Item'))], required=False))]),
        ),
        migrations.AlterField(
            model_name='journalpagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Displayed below the image in italics', max_length=255),
        ),
    ]
