# Generated by Django 3.0.10 on 2020-12-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('journal', '0007_journalindexpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalpage',
            old_name='image',
            new_name='banner',
        ),
        migrations.AddField(
            model_name='journalpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
