# Generated by Django 3.0.10 on 2021-01-21 18:22

from django.contrib.auth import get_user_model
from django.db import migrations


def make_many_authors(apps, schema_editor):
    """
        Adds the Author object in JournalPage.author to the
        many-to-many relationship in JournalPage.authors
    """
    JournalPage = apps.get_model('journal', 'JournalPage')

    for page in JournalPage.objects.all():
        User = apps.get_model('custom_user', 'User')
        default_author = User.objects.get(username='u6000791')
        if page.author is None:
            page.authors.add(default_author)
        else:
            page.authors.add(page.author)


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_journalpage_authors'),
    ]

    operations = [
        migrations.RunPython(make_many_authors),
    ]
