# Generated by Django 3.0.10 on 2021-01-21 20:07

from django.conf import settings
from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0019_remove_journalpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='author_posts', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
    ]
