# Generated by Django 3.0.10 on 2021-03-26 18:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_auto_20210121_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalindexpage',
            name='bottom_button_info',
            field=wagtail.core.fields.StreamField([('dropdown_button_list', wagtail.core.blocks.StructBlock([('list_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(label='Button Text', max_length=200)), ('info_text', wagtail.core.blocks.RichTextBlock(features=['h4', 'h5', 'bold', 'italic', 'link', 'ul'], label='Info Text'))]), label='Button'))]))], blank=True, null=True),
        ),
    ]
