# Generated by Django 3.0.10 on 2021-05-26 21:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_auto_20210327_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalindexpage',
            name='bottom_button_info',
            field=wagtail.core.fields.StreamField([('dropdown_button_list', wagtail.core.blocks.StructBlock([('list_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(label='Button Text', max_length=200)), ('info_text', wagtail.core.blocks.RichTextBlock(features=['h4', 'h5', 'bold', 'italic', 'link', 'document-link', 'ul'], label='Info Text'))]), label='Button'))]))], blank=True, help_text='Dropdown buttons appear below the list of child pages', null=True),
        ),
    ]
