# Generated by Django 5.2.17 on 2026-10-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_pushdelivery_leases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotification',
            options={'ordering': ['-created_at'], 'permissions': [('manage_push_notifications', 'Can manage push notifications')]},
        ),
    ]
