# Generated by Django 3.0.10 on 2020-10-20 22:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20201010_1158'),
        ('events', '0002_auto_20201008_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGeneralPage',
            fields=[
                ('generalpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.GeneralPage')),
                ('event_dates', models.CharField(max_length=200)),
                ('notes', wagtail.fields.RichTextField(blank=True, help_text='Notes will appear on the thumbnail image of the event on the event index page')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.generalpage',),
        ),
    ]
