# Generated by Django 3.0.10 on 2020-11-06 20:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201105_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
