# Generated by Django 3.0.10 on 2020-11-07 18:46

from django.db import migrations
import home.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventindexpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='body',
            field=wagtail.fields.StreamField([('green_heading', wagtail.blocks.CharBlock(help_text='Green centered text', max_length=200)), ('emphatic_text', home.models.EmphaticText(help_text='Red italic text', required=False)), ('paragraph', wagtail.blocks.StructBlock([('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')])), ('paragraph', wagtail.blocks.RichTextBlock())], classname='paragraph', required=True)), ('tan_bg_text', wagtail.blocks.RichTextBlock(classname='paragraph', help_text='Paragraph with a tan background', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title', max_length=200)), ('url', wagtail.blocks.URLBlock(label='URL')), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('html', wagtail.blocks.RawHTMLBlock(required=False)), ('image_list', wagtail.blocks.StructBlock([('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('title', wagtail.blocks.CharBlock(help_text='Displayed right of image in h2 tag, centered and uppercase', label='Title', max_length=200)), ('sub_title', wagtail.blocks.CharBlock(help_text='Displayed under title, centered and green', label='Subtitle', max_length=200)), ('text', wagtail.blocks.RichTextBlock(label='Text')), ('link_url', wagtail.blocks.URLBlock(help_text='If provided, the link will be applied to the image', label='Link URL', max_length=200, required=False))]), help_text='Images displayed with text to the right, all with a tan background', label='List Item'))], required=False)), ('page_link', wagtail.blocks.PageChooserBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('green_heading', wagtail.blocks.CharBlock(help_text='Green centered text', max_length=200)), ('emphatic_text', home.models.EmphaticText(help_text='Red italic text', required=False)), ('paragraph', wagtail.blocks.StructBlock([('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')])), ('paragraph', wagtail.blocks.RichTextBlock())], classname='paragraph', required=True)), ('tan_bg_text', wagtail.blocks.RichTextBlock(classname='paragraph', help_text='Paragraph with a tan background', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title', max_length=200)), ('url', wagtail.blocks.URLBlock(label='URL')), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('html', wagtail.blocks.RawHTMLBlock(required=False)), ('image_list', wagtail.blocks.StructBlock([('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('title', wagtail.blocks.CharBlock(help_text='Displayed right of image in h2 tag, centered and uppercase', label='Title', max_length=200)), ('sub_title', wagtail.blocks.CharBlock(help_text='Displayed under title, centered and green', label='Subtitle', max_length=200)), ('text', wagtail.blocks.RichTextBlock(label='Text')), ('link_url', wagtail.blocks.URLBlock(help_text='If provided, the link will be applied to the image', label='Link URL', max_length=200, required=False))]), help_text='Images displayed with text to the right, all with a tan background', label='List Item'))], required=False))]),
        ),
    ]
