# Generated by Django 3.0.10 on 2020-11-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201112_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Create a name for this policy', max_length=100)),
                ('link_text', models.CharField(help_text='This text will link to the provided policy page', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Policy Link',
            },
        ),
        migrations.AddField(
            model_name='eventpage',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.PolicyLink'),
        ),
    ]
