# Generated by Django 3.0.10 on 2020-11-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('events', '0013_auto_20201112_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='policylink',
            name='policy_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
