# Generated by Django 3.0.10 on 2020-12-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('events', '0016_auto_20201216_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='The thumbnail image is used when this page is displayed on another index page or is linked to via a page link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
