# Generated by Django 3.0.10 on 2021-02-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventpage_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='order_date',
        ),
    ]
