# Generated by Django 3.0.10 on 2021-02-19 18:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_remove_eventpage_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Unlike tags, categories can have a hierarchy so they can be more specifically organized.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.EventCategory')),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.AddField(
            model_name='eventpage',
            name='event_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='events.EventCategory'),
        ),
    ]
