# Generated by Django 5.2.8 on 2025-11-19 20:22

from django.db import migrations, models

def migrate_policy_to_policies(apps, schema_editor):
    EventPage = apps.get_model('events', 'EventPage')

    for event in EventPage.objects.all():
        if event.policy_id:  # If old ForeignKey had a value
            event.policies.add(event.policy_id)

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_alter_eventindexpage_body_alter_eventpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='event_policies', to='events.policylink'),
        ),
        migrations.RunPython(migrate_policy_to_policies),
        migrations.RemoveField(
            model_name='eventpage',
            name='policy',
        ),
    ]