# Generated by Django 5.2.8 on 2025-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_eventpage_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='event_policies', to='events.policylink'),
        ),
    ]
