# Generated by Django 5.2.9 on 2026-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_alter_eventpage_policies'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='image',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Structured end date/time. Optional — helpful for search engines and calendar integrations.', null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='member_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Numeric price for members (machine-readable). Enter a number like 0.00 for Free or 35.00. Leave blank to use 'Member cost' text.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='public_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric price for general public (machine-readable). Example: 35.00.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='purchase_url',
            field=models.URLField(blank=True, help_text='Optional direct registration/ticketing URL. If provided, search engines will use this when linking to the event page.', null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Structured start date/time for search engines. Example: 2026-03-25 10:00 AM. Use this (preferred) when the event has a single start time.', null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_dates',
            field=models.CharField(blank=True, default='', help_text="Date text for more flexibility. (e.g. 'September-October', 'All Summer', etc.) Prefer filling the Start Datetime and End Datetime when possible.", max_length=200),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='member_cost',
            field=models.CharField(blank=True, help_text="Price text for more flexibility (e.g. 'Free', '$35', '$25-$35'). Prefer filling the numeric field when possible.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='public_cost',
            field=models.CharField(blank=True, help_text="Price text for more flexibility (e.g. 'Free', '$35', '$25-$35'). Prefer filling the numeric field when possible.", max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventpage',
            constraint=models.CheckConstraint(condition=models.Q(('start_datetime__isnull', False), models.Q(('event_dates', ''), _negated=True), _connector='OR'), name='events_eventpage_start_or_event_dates_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='eventpage',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__isnull', True), ('start_datetime__isnull', False), _connector='OR'), name='events_eventpage_end_requires_start'),
        ),
    ]
