# Generated by Django 5.2.9 on 2026-01-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_remove_eventpage_image_eventpage_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='display_times_on_detail',
            field=models.BooleanField(default=True, help_text='Show start/end times on the event detail page (default on). Turn off to display dates only.'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='display_times_on_index',
            field=models.BooleanField(default=False, help_text='Show start/end times on the event index thumbnail (thumbnail space is limited; default off).'),
        ),
    ]
