# Generated by Django 5.2.9 on 2026-01-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_eventpage_display_times_on_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='display_times_on_detail',
            field=models.BooleanField(default=True, help_text='Show start/end times on the event detail page (default on). Turn off to display dates only.', verbose_name='Display times on detail page'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='display_times_on_index',
            field=models.BooleanField(default=False, help_text='Show start/end times (e.g. 9 AM) on the event index page thumbnail (thumbnail space is limited; default off).', verbose_name='Display times on event index page thumbnail'),
        ),
    ]
