# Generated by Codex on 2026-05-14

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_alter_eventindexpage_body_alter_eventpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='policies',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name='event_policies',
                to='events.policylink',
            ),
        ),
    ]
