# Generated by Django 3.0.10 on 2021-06-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['-name']},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
    ]
