# Generated by Django 3.0.10 on 2021-06-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20210629_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='plant_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
