# Generated by Django 3.0.10 on 2021-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20210628_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='planter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
