# Generated by Django 3.0.10 on 2021-06-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20210629_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='cultivar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
