# Generated by Django 3.0.10 on 2021-06-30 21:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20210630_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='bloom_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=255), blank=True, null=True, size=None),
        ),
    ]
