# Generated by Django 3.0.10 on 2021-06-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20210630_1526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
