# Generated by Django 3.0.10 on 2021-06-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20210630_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Location'),
        ),
    ]
