# Generated by Django 3.0.10 on 2021-06-30 22:52

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20210630_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='hardiness',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]), blank=True, null=True, size=13),
        ),
    ]
