# Generated by Django 3.0.10 on 2021-07-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_auto_20210630_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='water_regime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
