# Generated by Django 3.0.10 on 2021-07-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_species_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['-name'], 'verbose_name_plural': 'species'},
        ),
    ]
