# Generated by Django 3.0.10 on 2021-07-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_auto_20210706_1705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('genus', 'name', 'cultivar')},
        ),
    ]
