# Generated by Django 3.0.10 on 2021-07-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_auto_20210707_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='planter',
        ),
    ]
