# Generated by Django 3.0.10 on 2021-07-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('plants', '0017_auto_20210710_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='images',
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_images', to='plants.Species')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
