# Generated by Django 3.0.10 on 2021-07-10 21:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0018_auto_20210710_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='exposure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='plant_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='speciesimage',
            name='species',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_images', to='plants.Species'),
        ),
    ]
