# Generated by Django 3.0.10 on 2021-07-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0021_species_flower_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='vernacular_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
