# Generated by Django 3.0.10 on 2021-07-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0022_family_vernacular_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='garden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.GardenArea'),
        ),
    ]
