# Generated by Django 3.0.10 on 2021-07-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0023_auto_20210714_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='bee_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='deer_resist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='plant_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='rabbit_resist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='utah_native',
            field=models.BooleanField(default=False),
        ),
    ]
