# Generated by Django 3.0.10 on 2021-07-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0024_auto_20210714_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='commemoration_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='commemoration_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='plant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
