# Generated by Django 3.0.10 on 2021-07-15 18:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0027_auto_20210715_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='bloom_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255), blank=True, null=True, size=None),
        ),
    ]
