# Generated by Django 3.2.5 on 2021-09-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0029_speciesimage_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='high_elevation',
            field=models.BooleanField(default=False),
        ),
    ]
