# Generated by Django 3.2.5 on 2021-10-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0032_alter_gardenarea_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
    ]
