# Generated by Django 3.2.5 on 2021-10-15 22:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0035_auto_20211015_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='bloom_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Early January', 'Early January'), ('Mid January', 'Mid January'), ('Late January', 'Late January'), ('Early February', 'Early February'), ('Mid February', 'Mid February'), ('Late February', 'Late February'), ('Early March', 'Early March'), ('Mid March', 'Mid March'), ('Late March', 'Late March'), ('Early April', 'Early April'), ('Mid April', 'Mid April'), ('Late April', 'Late April'), ('Early May', 'Early May'), ('Mid May', 'Mid May'), ('Late May', 'Late May'), ('Early June', 'Early June'), ('Mid June', 'Mid June'), ('Late June', 'Late June'), ('Early July', 'Early July'), ('Mid July', 'Mid July'), ('Late July', 'Late July'), ('Early August', 'Early August'), ('Mid August', 'Mid August'), ('Late August', 'Late August'), ('Early September', 'Early September'), ('Mid September', 'Mid September'), ('Late September', 'Late September'), ('Early October', 'Early October'), ('Mid October', 'Mid October'), ('Late October', 'Late October'), ('Early November', 'Early November'), ('Mid November', 'Mid November'), ('Late November', 'Late November'), ('Early December', 'Early December'), ('Mid December', 'Mid December'), ('Late December', 'Late December'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255), blank=True, null=True, size=None),
        ),
    ]
