# Generated by Django 3.2.9 on 2022-08-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0037_alter_collection_plant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['name'], 'verbose_name_plural': 'genera'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.location'),
        ),
    ]
