# Generated by Django 4.1.3 on 2023-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0038_auto_20220817_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='genus',
            unique_together={('family', 'name')},
        ),
    ]
