# Generated by Django 4.1.3 on 2023-02-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0039_alter_genus_name_alter_genus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='habit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
