# Generated by Django 5.2.4 on 2025-08-07 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0040_alter_species_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, help_text='Optionally link to a related Blooming Now post. If left blank and species is set a link to the plant map for filtered to that species will be automatically generated.', null=True)),
                ('bloom_start', models.DateField(blank=True, null=True)),
                ('bloom_end', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.gardenarea')),
                ('collections', models.ManyToManyField(blank=True, to='plants.collection')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.species')),
            ],
        ),
    ]
