# Generated by Django 5.2.4 on 2025-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0041_bloomevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloomevent',
            name='bloom_end',
            field=models.DateField(blank=True, help_text='If left blank, the bloom start date will be used as the end date when displayed on calendars.', null=True),
        ),
    ]
