# Generated by Django 5.2.4 on 2025-08-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0042_alter_bloomevent_bloom_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloomevent',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what is blooming, where to see it and another other relevant info you think people might find interesting.', null=True),
        ),
        migrations.AlterField(
            model_name='bloomevent',
            name='title',
            field=models.CharField(blank=True, help_text="Optional title to describe what's blooming. If left blank, the species name will be used.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bloomevent',
            name='url',
            field=models.URLField(blank=True, help_text='Optionally link to a related Blooming Now post. If left blank and species is set a link to the plant map filtered to that species will be automatically generated.', null=True),
        ),
    ]
