# Generated by Django 5.2.4 on 2025-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0043_alter_bloomevent_description_alter_bloomevent_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloomevent',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what is blooming, where to see it and any other relevant info you think people might find interesting.', null=True),
        ),
    ]
