# Generated by Django 5.2.8 on 2025-11-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0044_alter_bloomevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='arborist_rec',
            field=models.BooleanField(default=False),
        ),
    ]
