# Generated by Django 5.2.15 on 2026-07-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0047_speciesautolinkindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='label_range_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
