# Generated by Django 5.2.9 on 2025-12-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cardholders_included', models.PositiveSmallIntegerField(default=1)),
                ('admissions_allowed', models.PositiveSmallIntegerField(default=1)),
                ('member_sale_ticket_allowance', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the membership level in USD.', max_digits=7)),
                ('purchase_url', models.URLField(blank=True, help_text='URL where this membership level can be purchased.', max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
