# Generated by Django 5.2.9 on 2025-12-17 19:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiplevel',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
