# Generated by Django 5.2.9 on 2026-01-28 16:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membershiplevel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiplevel',
            name='tooltip',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed on hover'),
        ),
    ]
