# Generated by Django 5.2.11 on 2026-02-06 00:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershiplevel_tooltip'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('dialog_display', models.BooleanField(blank=True, default=False, help_text='Should this dialog be displayed?', null=True)),
                ('dialog_title', models.CharField(blank=True, help_text='Title for pop-up dialog box', max_length=100, null=True)),
                ('dialog_content', wagtail.fields.RichTextField(blank=True, help_text='Main content of the dialog box', null=True)),
                ('dialog_style', models.CharField(blank=True, choices=[('corner', 'Corner'), ('full', 'Full Page')], max_length=6, null=True)),
                ('body', wagtail.fields.StreamField([('carousel', 5)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose an internal page', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Or enter an external URL (will be used if no internal page selected)', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Open the link in a new tab', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1), ('link_page', 2), ('link_url', 3), ('open_in_new_tab', 4)]], {})})),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('custom_css', models.ForeignKey(blank=True, help_text='Upload a CSS file to apply custom styling to this page. Note that editing an existing document will apply the changes to ALL pages where the document is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Custom CSS')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='You only need to add a thumbnail if this page is the child of a another page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
