# Generated by Django 5.2.11 on 2026-02-06 17:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_membershippage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippage',
            name='body',
            field=wagtail.fields.StreamField([('carousel', 0), ('pricing_card', 13)], block_lookup={0: ('memberships.blocks.LinkedCarouselBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Flexible Options for your Unique Situation', 'help_text': 'Main heading for the card', 'required': True}), 2: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 0, 'help_text': 'Price for the first cardholder (numbers only, no $ sign).', 'max_digits': 10, 'required': True}), 3: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 0, 'help_text': 'Price for each additional cardholder.', 'max_digits': 10, 'required': True}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Maximum number of additional cardholders (e.g. 3).', 'required': False}), 5: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 0, 'help_text': 'Price per guest for garden visits.', 'max_digits': 10, 'required': True}), 6: ('wagtail.blocks.IntegerBlock', (), {'default': 8, 'help_text': 'Maximum number of guests allowed (e.g. 8).', 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': "If unchecked, don't render the 'Two tickets per show: included' line.", 'required': False}), 8: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 0, 'help_text': 'Price to increase to four tickets per show. Leave blank if not offered.', 'max_digits': 10, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who qualifies for the 4-ticket upgrade (e.g. "Experience level memberships with 4 or more total visitors")', 'required': False}), 10: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 0, 'help_text': 'Price to increase to six tickets per show. Leave blank if not offered.', 'max_digits': 10, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who qualifies for the 6-ticket upgrade (e.g. "Experience Plus level memberships with 6 or more total visitors")', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': "Small italic footer note (e.g. '*An upgraded Concert Access Level does not guarantee ticket availability.')", 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 1), ('first_cardholder_price', 2), ('additional_cardholder_price', 3), ('additional_cardholder_max', 4), ('guest_admission_price', 5), ('guest_admission_max', 6), ('two_tickets_included', 7), ('four_tickets_price', 8), ('four_tickets_qualifier', 9), ('six_tickets_price', 10), ('six_tickets_qualifier', 11), ('footer_note', 12)]], {})}),
        ),
    ]
