# Generated by Django 5.2.11 on 2026-02-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0012_alter_membershippage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this label group')),
                ('cardholder_label', models.CharField(help_text="Label used for cardholders, e.g. 'Cardholders'")),
                ('admissions_label', models.CharField(help_text="Label used for admissions, e.g. 'Guests per visit'")),
                ('member_tickets_label', models.CharField(help_text="Label for member tickets, e.g. 'Member concert tickets'")),
            ],
        ),
        migrations.AddField(
            model_name='membershiplevel',
            name='labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membershiplabel'),
        ),
    ]
