# Generated by Django 5.2.11 on 2026-02-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0014_alter_membershippage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_header_text', models.CharField(help_text='Header text above membership widget')),
                ('cardholder_help_hover', models.CharField(help_text='Help text to appear when hovering over question mark beside cardholder entry field')),
                ('admissions_help_hover', models.CharField(help_text='Help text to appear when hovering over question mark beside admissions entry field')),
                ('member_tickets_help_hover', models.CharField(help_text='Help text to appear when hovering over question mark beside member tickets entry field')),
            ],
            options={
                'verbose_name': 'Membership widget configuration',
                'verbose_name_plural': 'Membership widget configuration',
            },
        ),
    ]
