# Generated by Django 5.2.11 on 2026-02-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0015_membershipwidgetconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipwidgetconfig',
            name='admissions_label',
            field=models.CharField(default='Additional Admission Guest Entry', help_text='Label used for admissions'),
        ),
        migrations.AddField(
            model_name='membershipwidgetconfig',
            name='cardholder_label',
            field=models.CharField(default='Cardholders', help_text='Label used for cardholders'),
        ),
        migrations.AddField(
            model_name='membershipwidgetconfig',
            name='member_tickets_label',
            field=models.CharField(default='Concert Series Pre-Sale Member Tickets', help_text='Label for member tickets'),
        ),
        migrations.AddField(
            model_name='membershipwidgetconfig',
            name='page_header_text',
            field=models.CharField(default='Find the best membership for you', help_text='Header text at top of page'),
        ),
        migrations.AlterField(
            model_name='membershipwidgetconfig',
            name='widget_header_text',
            field=models.CharField(default='Your needs', help_text='Header text above membership widget form inputs'),
        ),
    ]
