# Generated by Django 5.2.11 on 2026-02-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0016_membershipwidgetconfig_admissions_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipwidgetconfig',
            name='presale_qualification_error_message_template',
            field=models.TextField(default='To qualify for Red Butte Garden Outdoor Concert Member Presale access at the {tickets} ticket level, please add a combination of cardholders and guests that is equal to or greater than {tickets}.', help_text='Use {tickets} as a placeholder. Example output will replace {tickets} with 2, 4, or 6.'),
        ),
    ]
