# Generated by Django 5.2.11 on 2026-02-12 18:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0017_membershipwidgetconfig_presale_qualification_error_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiplevel',
            name='charitable_gift_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Charitable gift amount in USD.', max_digits=7),
        ),
    ]
