# Generated by Django 5.2.11 on 2026-02-13 17:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0018_membershiplevel_charitable_gift_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipwidgetconfig',
            name='auto_renewal_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Auto renewal discount amount in USD. Set to zero to disable.', max_digits=4),
        ),
    ]
