# Generated by Django 5.2.11 on 2026-02-20 00:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0023_alter_membershippage_body'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membershiplevel',
            constraint=models.UniqueConstraint(fields=('cardholders_included', 'admissions_allowed', 'member_sale_ticket_allowance'), name='uniq_membership_level_entitlements'),
        ),
        migrations.AddConstraint(
            model_name='membershiplevel',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='chk_membership_level_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='membershiplevel',
            constraint=models.CheckConstraint(condition=models.Q(('charitable_gift_amount__gte', Decimal('0.00'))), name='chk_membership_level_gift_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='membershiplevel',
            constraint=models.CheckConstraint(condition=models.Q(('charitable_gift_amount__lte', models.F('price'))), name='chk_membership_level_gift_lte_price'),
        ),
    ]
