# Generated by Django 3.0.10 on 2020-10-07 17:41

from django.db import migrations, models
import django.db.models.deletion
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
        ('concerts', '0002_auto_20201006_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorPackagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('heading', home.models.Heading(classname='full title', help_text='Text will be green and centered')), ('emphatic_text', home.models.EmphaticText(classname='full title', help_text='Text will be red, italic and centered')), ('paragraph', wagtail.core.blocks.RichTextBlock(classname='paragraph', required=True)), ('tan_bg_text', wagtail.core.blocks.RichTextBlock(classname='paragraph', help_text='Paragraph with a tan background', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('sponsor_list', wagtail.core.blocks.StructBlock([('list_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('sponsor_title', wagtail.core.blocks.CharBlock(label='Sponsor Title', max_length=200)), ('sponsor_url', wagtail.core.blocks.URLBlock(label='URL to sponsor website')), ('sponsor_logo', wagtail.images.blocks.ImageChooserBlock())]), label='Sponsors'))])), ('button_table', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(label='Button text')), ('table_list', wagtail.core.blocks.StreamBlock([('title', home.models.Heading()), ('table', wagtail.contrib.table_block.blocks.TableBlock())]))]))])),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
