# Generated by Django 3.0.10 on 2020-10-08 21:25

from django.db import migrations
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_auto_20201008_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpackagepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', home.models.Heading(classname='full title', help_text='Text will be green and centered')), ('emphatic_text', home.models.EmphaticText(classname='full title', help_text='Text will be red, italic and centered')), ('paragraph', wagtail.core.blocks.StructBlock([('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')])), ('paragraph', wagtail.core.blocks.RichTextBlock())], classname='paragraph', required=True)), ('tan_bg_text', wagtail.core.blocks.RichTextBlock(classname='paragraph', help_text='Paragraph with a tan background', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('sponsor_list', wagtail.core.blocks.StructBlock([('list_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('sponsor_title', wagtail.core.blocks.CharBlock(label='Sponsor Title', max_length=200)), ('sponsor_url', wagtail.core.blocks.URLBlock(label='URL to sponsor website')), ('sponsor_logo', wagtail.images.blocks.ImageChooserBlock())]), label='Sponsors'))])), ('button_table', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(label='Button text')), ('table_list', wagtail.core.blocks.StreamBlock([('title', home.models.Heading()), ('table', wagtail.contrib.table_block.blocks.TableBlock(help_text='Right-click to add/remove rows/columns', table_options={'autoColumnSize': False, 'colHeaders': True, 'editor': 'text', 'height': 216, 'language': 'en-US', 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': True, 'startCols': 6, 'startRows': 3, 'stretchH': 'all'}))]))])), ('table_cards', wagtail.core.blocks.StructBlock([('list_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('body', wagtail.core.blocks.StreamBlock([('heading', home.models.Heading()), ('paragraph', wagtail.core.blocks.StructBlock([('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')])), ('paragraph', wagtail.core.blocks.RichTextBlock())])), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': False, 'colHeaders': True, 'editor': 'text', 'height': 216, 'language': 'en-US', 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': True, 'startCols': 4, 'startRows': 2, 'stretchH': 'all'}))]))]), label='List of info cards with tables'))]))]),
        ),
    ]
