# Generated by Django 3.0.10 on 2021-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0011_auto_20210112_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertpage',
            name='banner_link',
            field=models.URLField(blank=True, help_text='Where to direct the banner image link'),
        ),
    ]
