# Generated by Django 3.0.10 on 2021-01-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0014_auto_20210112_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='member_price',
            field=models.CharField(blank=True, default='$', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='public_price',
            field=models.CharField(default='$', max_length=100),
        ),
    ]
