# Generated by Django 3.0.10 on 2021-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0017_auto_20210112_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
