# Generated by Django 3.0.10 on 2021-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0018_concert_available_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='available_until',
            field=models.DateField(blank=True, help_text='Date that on-demand virtual concert will remain available until', null=True),
        ),
    ]
