# Generated by Django 3.0.10 on 2021-01-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0019_auto_20210113_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='ticket_url',
            field=models.URLField(default='https://redbuttegarden.ticketfly.com'),
        ),
    ]
