# Generated by Django 3.0.10 on 2021-01-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0020_concert_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
