# Generated by Django 3.0.10 on 2021-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0021_concert_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concert',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
    ]
