# Generated by Django 3.0.10 on 2021-04-30 21:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('concerts', '0032_auto_20210311_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastConcertPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('lineups', wagtail.fields.StreamField([('lineup', wagtail.blocks.StructBlock([('year', wagtail.blocks.IntegerBlock(min_value=1980, required=True)), ('poster', wagtail.images.blocks.ImageChooserBlock(required=True)), ('artists', wagtail.blocks.RichTextBlock(required=True))]))])),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='You only need to add a thumbnail if this page is the child of a another page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
