# Generated by Django 3.2.9 on 2022-10-27 18:37

from django.db import migrations
import home.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0039_donorschedulepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorpackagepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', home.models.Heading(form_classname='full title', help_text='Text will be green and centered')), ('emphatic_text', home.models.EmphaticText(form_classname='full title', help_text='Text will be red, italic and centered')), ('paragraph', wagtail.core.blocks.StructBlock([('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('text-center', 'Center'), ('right', 'Right')])), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default'), ('tan-bg', 'Tan'), ('green-bg', 'Green'), ('dark-tan-bg', 'Dark Tan'), ('white-bg', 'White'), ('red-bg', 'Red'), ('orange-bg', 'Orange')])), ('paragraph', wagtail.core.blocks.RichTextBlock())], classname='paragraph', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('sponsor_list', wagtail.core.blocks.StructBlock([('list_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('sponsor_title', wagtail.core.blocks.CharBlock(label='Sponsor Title', max_length=200, required=False)), ('sponsor_url', wagtail.core.blocks.URLBlock(label='URL to sponsor website')), ('sponsor_logo', wagtail.images.blocks.ImageChooserBlock())]), label='Sponsors'))])), ('button_table', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(label='Button text')), ('table_list', wagtail.core.blocks.StreamBlock([('title', home.models.Heading()), ('table', wagtail.contrib.table_block.blocks.TableBlock(help_text='Right-click to add/remove rows/columns', table_options={'autoColumnSize': False, 'colHeaders': True, 'editor': 'text', 'height': 216, 'language': 'en-US', 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': True, 'startCols': 6, 'startRows': 3, 'stretchH': 'all'}))]))])), ('table_cards', wagtail.core.blocks.StructBlock([('list_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('body', wagtail.core.blocks.StreamBlock([('heading', home.models.Heading()), ('paragraph', wagtail.core.blocks.StructBlock([('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('text-center', 'Center'), ('right', 'Right')])), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default'), ('tan-bg', 'Tan'), ('green-bg', 'Green'), ('dark-tan-bg', 'Dark Tan'), ('white-bg', 'White'), ('red-bg', 'Red'), ('orange-bg', 'Orange')])), ('paragraph', wagtail.core.blocks.RichTextBlock())])), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': False, 'colHeaders': True, 'editor': 'text', 'height': 216, 'language': 'en-US', 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': True, 'startCols': 4, 'startRows': 2, 'stretchH': 'all'}))]))]), label='List of info cards with tables'))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(help_text='Right-click to add/remove rows/columns', table_options={'autoColumnSize': False, 'colHeaders': False, 'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut---------', 'alignment'], 'editor': 'text', 'height': 216, 'language': 'en-US', 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': True, 'startCols': 4, 'startRows': 3, 'stretchH': 'all'}))]),
        ),
    ]
