# Generated by Django 4.1.3 on 2023-03-02 21:42

import datetime
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0046_alter_concertpage_dialog_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertpage',
            name='body',
            field=wagtail.fields.StreamField([('concerts', wagtail.blocks.StructBlock([('band_img', wagtail.images.blocks.ImageChooserBlock(required=True)), ('hidden', wagtail.blocks.BooleanBlock(default=True, help_text='If hidden box is checked, concert will not be displayed on the page', required=False)), ('on_sale', wagtail.blocks.BooleanBlock(default=True, help_text='If unchecked, Buy Tickets button will be grayed out', required=False)), ('virtual', wagtail.blocks.BooleanBlock(default=False, help_text='Is this a virtual concert?', required=False)), ('canceled', wagtail.blocks.BooleanBlock(default=False, required=False)), ('postponed', wagtail.blocks.BooleanBlock(default=False, required=False)), ('sold_out', wagtail.blocks.BooleanBlock(default=False, required=False)), ('available_until', wagtail.blocks.DateTimeBlock(blank=True, help_text='Date that on-demand virtual concert will remain available until', null=True, required=False)), ('band_info', wagtail.blocks.RichTextBlock(help_text='Provide the names of the bands/openers and any other info here. Text will be centered.')), ('concert_dates', wagtail.blocks.ListBlock(wagtail.blocks.DateTimeBlock())), ('gates_time', wagtail.blocks.TimeBlock(blank=True, default=datetime.time(18, 0), null=True, required=False)), ('show_time', wagtail.blocks.TimeBlock(blank=True, default=datetime.time(19, 0), null=True, required=False)), ('member_price', wagtail.blocks.CharBlock(blank=True, default='$', max_length=100, null=True)), ('public_price', wagtail.blocks.CharBlock(default='$', max_length=100)), ('ticket_url', wagtail.blocks.URLBlock(default='https://redbuttegarden.ticketfly.com'))])), ('paragraph', wagtail.blocks.StructBlock([('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('text-center', 'Center'), ('right', 'Right')])), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('default', 'Default'), ('tan-bg', 'Tan'), ('green-bg', 'Green'), ('dark-tan-bg', 'Dark Tan'), ('white-bg', 'White'), ('red-bg', 'Red'), ('orange-bg', 'Orange')])), ('paragraph', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
