# Generated by Django 4.1.3 on 2023-03-03 19:08

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0049_alter_concertpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertpage',
            name='wave_one_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed at the top of the list of concerts'),
        ),
        migrations.AddField(
            model_name='concertpage',
            name='wave_two_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed above any wave 2 concerts (if there are any)'),
        ),
    ]
