# Generated by Django 4.1.10 on 2024-01-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0056_concert_concertdonorclubpackage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['-year', 'name']},
        ),
        migrations.AlterModelOptions(
            name='concertdonorclubmember',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='concertdonorclubpackage',
            options={'ordering': ['-year', 'name']},
        ),
        migrations.AlterField(
            model_name='concertdonorclubmember',
            name='additional_concerts',
            field=models.ManyToManyField(blank=True, to='concerts.concert'),
        ),
    ]
