# Generated by Django 4.1.10 on 2024-01-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0057_alter_concert_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.PositiveBigIntegerField()),
                ('serial', models.PositiveBigIntegerField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.concert')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.concertdonorclubmember')),
            ],
            options={
                'ordering': ['barcode', 'concert__name'],
            },
        ),
    ]
