# Generated by Django 4.1.10 on 2024-01-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0058_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='barcode',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='serial',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
