# Generated by Django 4.1.10 on 2024-01-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0060_remove_ticket_serial_ticket_order_id_ticket_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertdonorclubmember',
            name='additional_concerts',
        ),
    ]
