# Generated by Django 4.1.10 on 2024-02-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0063_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets'),
        ),
    ]
