# Generated by Django 4.1.10 on 2024-02-08 20:03

import concerts.models
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0066_alter_concertdonorclubmember_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertdonorclubticketsalepage',
            name='body',
            field=wagtail.fields.StreamField([('chat', concerts.models.CometChatBlock()), ('paragraph', wagtail.blocks.StructBlock([('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('text-center', 'Center'), ('right', 'Right')])), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('default', 'Default'), ('tan-bg', 'Tan'), ('green-bg', 'Green'), ('dark-tan-bg', 'Dark Tan'), ('white-bg', 'White'), ('red-bg', 'Red'), ('orange-bg', 'Orange')])), ('paragraph', wagtail.blocks.RichTextBlock())], classname='paragraph', required=True))], use_json_field=True),
        ),
    ]
