# Generated by Django 4.1.10 on 2024-04-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0068_concertdonorclubportalpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('ISSUED', 'Issued'), ('REDEEMED', 'Redeemed'), ('RESERVED', 'Reserved')], max_length=20, null=True),
        ),
    ]
