# Generated by Django 4.1.10 on 2024-04-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0069_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['begin', 'name']},
        ),
    ]
