# Generated by Django 4.1.10 on 2024-04-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0070_alter_concert_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
