# Generated by Django 4.1.10 on 2024-04-26 17:09

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0073_alter_concertpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertpage',
            name='presale_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed above any presale concerts'),
        ),
        migrations.AddField(
            model_name='concertpage',
            name='wave_one_sale_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='concertpage',
            name='wave_one_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed above any wave 1 concerts concerts'),
        ),
        migrations.AlterField(
            model_name='concertpage',
            name='wave_two_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed above any wave 2 concerts'),
        ),
    ]
