# Generated by Django 4.1.10 on 2024-04-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0074_concertpage_presale_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertpage',
            name='wave_one_sale_date',
        ),
    ]
