# Generated by Django 4.1.10 on 2024-06-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0075_remove_concertpage_wave_one_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
