# Generated by Django 4.2.17 on 2025-03-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0079_oauth2token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantContactCDCListSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdc_list_id', models.CharField(help_text='List ID for the Concert Donor Club list in Constant Contact', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='concertdonorclubmember',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concertdonorclubmember',
            name='constant_contact_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
