# Generated by Django 4.2.20 on 2025-03-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0080_constantcontactcdclistsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertDonorClubMemberGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(to='concerts.concertdonorclubmember')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.concertdonorclubpackage')),
            ],
        ),
    ]
