# Generated by Django 4.2.20 on 2025-04-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0080_constantcontactcdclistsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertDonorClubMemberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to='concerts.concertdonorclubmember')),
            ],
        ),
    ]
