# Generated by Django 4.2.20 on 2025-04-04 19:59

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0081_concertdonorclubmembergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertdonorclubmember',
            name='chat_access_token',
            field=models.CharField(blank=True, help_text='This is used to store the Dead Simple Chat access token for this user.', max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='concertdonorclubticketsalepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 3)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('text-center', 'Center'), ('right', 'Right')]}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('tan-bg', 'Tan'), ('green-bg', 'Green'), ('dark-tan-bg', 'Dark Tan'), ('white-bg', 'White'), ('red-bg', 'Red'), ('orange-bg', 'Orange')]}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('alignment', 0), ('background_color', 1), ('paragraph', 2)]], {'classname': 'paragraph', 'required': True})}),
        ),
    ]
