# Generated by Django 4.2.20 on 2025-05-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0083_alter_concertdonorclubmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertdonorclubmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
