# Generated by Django 4.2.20 on 2025-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0085_ticket_etix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='etix_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
