# Generated by Django 5.2.4 on 2025-07-16 19:41

import datetime
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0086_alter_ticket_etix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertpage',
            name='body',
            field=wagtail.fields.StreamField([('concerts', 16)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [(0, 'Presale'), (1, 'Wave 1'), (2, 'Wave 2')], 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If hidden box is checked, concert will not be displayed on the page', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If unchecked, Buy Tickets button will be grayed out', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Is this a virtual concert?', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 6: ('wagtail.blocks.DateTimeBlock', (), {'blank': True, 'help_text': 'Date that on-demand virtual concert will remain available until', 'null': True, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'blank': False, 'help_text': 'Name of the band or artist performing at the concert.', 'label': 'Band Name', 'max_length': 200, 'required': True}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Provide the names of the bands/openers and any other info here. Text will be centered.'}), 9: ('wagtail.blocks.DateTimeBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.TimeBlock', (), {'blank': True, 'default': datetime.time(18, 0), 'null': True, 'required': False}), 12: ('wagtail.blocks.TimeBlock', (), {'blank': True, 'default': datetime.time(19, 0), 'null': True, 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '$', 'max_length': 100, 'null': True}), 14: ('wagtail.blocks.CharBlock', (), {'default': '$', 'max_length': 100}), 15: ('wagtail.blocks.URLBlock', (), {'default': 'https://www.etix.com/ticket/e/1049536/2025-red-butte-season-salt-lake-city-red-butte-garden-arboretum', 'label': 'Ticket URL'}), 16: ('wagtail.blocks.StructBlock', [[('band_img', 0), ('wave', 1), ('hidden', 2), ('on_sale', 3), ('virtual', 4), ('canceled', 5), ('postponed', 5), ('sold_out', 5), ('available_until', 6), ('band_name', 7), ('band_info', 8), ('concert_dates', 10), ('gates_time', 11), ('show_time', 12), ('member_price', 13), ('public_price', 14), ('ticket_url', 15)]], {})}, null=True),
        ),
    ]
