# Generated by Django 5.2.12 on 2026-03-17 18:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0093_alter_concertpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Headings must be used sequentially. In other words, if you want to use an h3 it must appear after an h2 and be part of the same context/section. Do not use heading tags (e.g. h2, h3) to emphasize text. Lead can be used to make slightly larger text for emphasis. Provide the names of the bands/openers and any other info here. Text will be centered.'),
        ),
        migrations.AlterField(
            model_name='concertpage',
            name='presale_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed above any presale concerts. Headings must be used sequentially. In other words, if you want to use an h3 it must appear after an h2 and be part of the same context/section. Do not use heading tags (e.g. h2, h3) to emphasize text. Lead can be used to make slightly larger text for emphasis. Provide the names of the bands/openers and any other info here. Text will be centered.'),
        ),
        migrations.AlterField(
            model_name='concertpage',
            name='wave_one_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed above any wave 1 concerts concerts. Headings must be used sequentially. In other words, if you want to use an h3 it must appear after an h2 and be part of the same context/section. Do not use heading tags (e.g. h2, h3) to emphasize text. Lead can be used to make slightly larger text for emphasis. Provide the names of the bands/openers and any other info here. Text will be centered.'),
        ),
        migrations.AlterField(
            model_name='concertpage',
            name='wave_two_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='Displayed above any wave 2 concerts. Headings must be used sequentially. In other words, if you want to use an h3 it must appear after an h2 and be part of the same context/section. Do not use heading tags (e.g. h2, h3) to emphasize text. Lead can be used to make slightly larger text for emphasis. Provide the names of the bands/openers and any other info here. Text will be centered.'),
        ),
    ]
