# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0096_alter_concertdonorclubportalpage_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcertDonorClubWelcomeListAdd",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("added", "Added"),
                            ("already_member", "Already member"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("roster_sync", "Roster sync"),
                            ("manual", "Manual"),
                            ("backfill", "Backfill"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("contact_id", models.UUIDField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempted_at", models.DateTimeField(blank=True, null=True)),
                ("added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcome_list_adds",
                        to="concerts.concertdonorclubmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "list_id"], name="concerts_co_status_a15621_idx"),
                    models.Index(fields=["member", "list_id"], name="concerts_co_member__ca9e42_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "list_id"),
                        name="unique_cdc_welcome_list_add_per_member_list",
                    ),
                ],
            },
        ),
    ]
