# Generated by Django 5.2.16 on 2026-09-25 18:22

import datetime
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0097_concertdonorclubwelcomelistadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertpage',
            name='body',
            field=wagtail.fields.StreamField([('concerts', 16)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Optional but recommended name of the band(s)/artist(s) performing. Text in this field is not displayed on the concert page so you should also include the band names in the Band Info section below. This field is used when generating iCal event titles and for displaying concert buy links on the home page on the day of the concert if not sold out.', 'label': 'Band Name', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'bold', 'italic', 'link', 'ol', 'ul', 'lead'], 'help_text': 'Headings must be used sequentially. In other words, if you want to use an h3 it must appear after an h2 and be part of the same context/section. Do not use heading tags (e.g. h2, h3) to emphasize text. Lead (Ld) can be used to make slightly larger text for emphasis. Provide the names of the bands/openers and any other info here. Text will be centered.'}), 3: ('wagtail.blocks.DateTimeBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.TimeBlock', (), {'blank': True, 'default': datetime.time(18, 0), 'null': True, 'required': False}), 6: ('wagtail.blocks.TimeBlock', (), {'blank': True, 'default': datetime.time(19, 0), 'null': True, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '$', 'max_length': 100, 'null': True}), 8: ('wagtail.blocks.CharBlock', (), {'default': '$', 'max_length': 100}), 9: ('wagtail.blocks.URLBlock', (), {'default': 'https://www.etix.com/ticket/e/1049536/2025-red-butte-season-salt-lake-city-red-butte-garden-arboretum', 'label': 'Ticket URL'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [(0, 'Presale'), (1, 'Wave 1'), (2, 'Wave 2')], 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If hidden box is checked, concert will not be displayed on the page', 'required': False}), 12: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If unchecked, Buy Tickets button will be grayed out', 'required': False}), 13: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Is this a virtual concert?', 'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 15: ('wagtail.blocks.DateTimeBlock', (), {'blank': True, 'help_text': 'Date that on-demand virtual concert will remain available until', 'null': True, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('band_img', 0), ('band_name', 1), ('band_info', 2), ('concert_dates', 4), ('gates_time', 5), ('show_time', 6), ('member_price', 7), ('public_price', 8), ('ticket_url', 9), ('wave', 10), ('hidden', 11), ('on_sale', 12), ('virtual', 13), ('canceled', 14), ('postponed', 14), ('sold_out', 14), ('available_until', 15)]], {})}, null=True),
        ),
    ]
