# Generated by Django 3.0.10 on 2021-07-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantAPIGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('roles', models.ManyToManyField(blank=True, related_name='apigroups', to='auth.Group', verbose_name='Role')),
            ],
        ),
    ]
