# Generated by Django 4.1.10 on 2024-01-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'username']},
        ),
    ]
