# Generated by Django 3.0.10 on 2021-07-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_plantapigroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantAPIGroup',
        ),
    ]
